name: Publish npm package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/
      - run: bun install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
